name: Resuable Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
        description: The branch ref to build. Leave empty to use workflow branch.
      publish:
        type: boolean
        default: false
        description: To publish the project artifacts on Bonita Artifact Repository.
      release:
        type: boolean
        default: false
        description: To indicate that the current build is for a release (it will publish artifacts as well).

    secrets:
      BONITA_CI_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bonitasoft/bonita-user-application
          token: ${{ secrets.BONITA_CI_PAT }}
          ref: ${{ inputs.ref }}

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Maven Build
        if: ${{ !inputs.publish }}
        timeout-minutes: 60
        run: ./mvnw -ntp verify

      - name: Maven Build & Deploy snapshot
        if: ${{ inputs.publish && !inputs.release }}
        timeout-minutes: 60
        run: ./mvnw -ntp deploy -DaltDeploymentRepository=snapshots::${{ vars.SNAPSHOTS_REPOSITORY_URL }}

      - name: Maven Build & Deploy release
        if: ${{ inputs.release }}
        timeout-minutes: 60
        run: ./mvnw -ntp deploy -DaltDeploymentRepository=staging::${{ vars.STAGING_REPOSITORY_URL }}

      - name: Upload BOS to the Github release
        if: ${{ inputs.release }}
        env:
          GH_TOKEN: ${{ secrets.BONITA_CI_PAT }}
        run: gh release upload ${{ inputs.ref }} ./target/bonita-user-application-${{ inputs.ref }}.bos --repo bonitasoft/bonita-user-application

      - name: Extract secrets from Keeper
        if: ${{ inputs.release }}
        uses: Keeper-Security/ksm-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_BOS_REDIRECT_RECORD_ID }}/field/login > env:BOS_REDIRECT_USER
            ${{ vars.KEEPER_BOS_REDIRECT_RECORD_ID }}/field/password > env:BOS_REDIRECT_PSW

      - name: Update BOS redirect table
        if: ${{ inputs.release }}
        env:
          REDIRECT_ID: ${{ vars.BOS_REDIRECT_USER_APP_ID }}
          BOS_REDIRECT_URL: https://redirect.bonitasoft.com/
          BOS_RELEASE_ASSET_URL: https%3A%2F%2Fgithub.com%2Fbonitasoft%2Fbonita-user-application%2Freleases%2Fdownload%2F${{ inputs.ref }}%2Fbonita-user-application-${{ inputs.ref }}.bos
        run: | 
          MAINTENANCE_VERSION="$(cut -d '.' -f3 <<< ${{ inputs.ref }})"
          MAJOR_VERSION="$(cut -d '.' -f1,2 <<< ${{ inputs.ref }})"
          STATUS_CODE=$(curl -s -o /dev/null -L -w "%{http_code}\\n" "$BOS_REDIRECT_URL" -u "$BOS_REDIRECT_USER:$BOS_REDIRECT_PSW" -H "Content-Type: application/x-www-form-urlencoded" --data "id=$REDIRECT_ID&product=bos&major_version=$MAJOR_VERSION&minor_version=$MAINTENANCE_VERSION&URL=$BOS_RELEASE_ASSET_URL&description=Bonita+User+App&submit=true")
          if [ $STATUS_CODE!="200" ] 
          then
              echo "Redirect entry for tuple ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) already exists. Performing update..."
              STATUS_CODE=$(curl -s -o /dev/null -L -w "%{http_code}\\n" "$BOS_REDIRECT_URL" -u "$BOS_REDIRECT_USER:$BOS_REDIRECT_PSW" -H "Content-Type: application/x-www-form-urlencoded" --data "action=modify&id=$REDIRECT_ID&product=bos&major_version=$MAJOR_VERSION&minor_version=$MAINTENANCE_VERSION&URL=$BOS_RELEASE_ASSET_URL&description=Bonita+User+App&submit_modify=true")
              if [ $STATUS_CODE!="200" ] 
              then
                echo "Failed to update BOS redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) with new URL: $BOS_RELEASE_ASSET_URL"
              else
                echo "BOS Redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) updated with URL: $BOS_RELEASE_ASSET_URL"
              fi   
          else
              echo "BOS Redirect entry ($REDIRECT_ID,$MAJOR_VERSION,$MAINTENANCE_VERSION) created with URL: $BOS_RELEASE_ASSET_URL"
          fi
