name: Update Version

on:
  workflow_call: 
    inputs:
      version:
        type: string
        required: true
      merge-upstream-ignoring-conflicts:
        type: boolean
        default: false
    secrets:
      KSM_CONFIG:
        required: true
      BONITA_CI_PAT:
        required: true

jobs:
  update-version:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4
        with:
          repository: bonitasoft/bonita-user-application
          ref: ${{ github.ref }}
          token: ${{ secrets.BONITA_CI_PAT }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Maven
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Update version
        run: ./mvnw -B -ntp versions:set -DnewVersion=${{ inputs.version }}

      - name: Git Setup
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Commit and push
        run: |
          git commit -a -m "chore(versioning): update version to ${{ inputs.version }}"
          git push

  merge-upstream:
    needs: update-version
    if: ${{ inputs.merge-upstream-ignoring-conflicts }}
    runs-on: ubuntu-24.04
    steps:
      - name: Setup git
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Determine upstream branch
        id: upstream-branch
        run: echo "ref=${{ fromJson(vars.SUPPORTED_BRANCHES).upstream-branch[github.ref_name] }}" >> $GITHUB_OUTPUT

      - name: Checkout upstream branch
        uses: actions/checkout@v4
        with:
          repository: bonitasoft/bonita-user-application
          ref: ${{ steps.upstream-branch.outputs.ref }}
          fetch-depth: 0
          token: ${{ secrets.BONITA_CI_PAT }}

      - name: Merge upstream branch
        run: |
           git config merge.ours.driver true
           git merge origin/${{ github.ref_name }} -X ours  -m "chore(merge): ${{ github.ref_name }} into ${{ steps.upstream-branch.outputs.ref }}"
           git push