name: Create Tag

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      BONITA_CI_PAT:
        required: true
      KSM_CONFIG:
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: bonitasoft/bonita-user-application
          token: ${{ secrets.BONITA_CI_PAT }}
          ref: ${{ github.ref }}

      - name: Git Setup
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Create Release Branch
        run: git checkout -B release/${{ inputs.version }}

      - name: Change Version
        run: ./mvnw -ntp versions:set -DnewVersion=${{ inputs.version }}

      - name: Commit and Push Tag
        run: |
          git commit -a -m "release(${{ inputs.version }}) create release ${{ inputs.version }}" 
          git tag -a ${{ inputs.version }} -m "Release ${{ inputs.version }}"
          git push origin ${{ inputs.version }}:${{ inputs.version }}

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.BONITA_CI_PAT }}
        run: gh release create ${{ inputs.version }} --generate-notes --repo bonitasoft/bonita-user-application
