name: Update Version

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      merge-upstream-ignoring-conflicts:
        type: boolean
        default: false
    secrets:
      KSM_CONFIG:
        required: true
      BONITA_CI_PAT:
        required: true

jobs:
  update-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: bonitasoft/bonita-user-application
          ref: ${{ github.ref }}
          token: ${{ secrets.BONITA_CI_PAT }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Setup Maven
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Update version
        run: ./mvnw -B -ntp versions:set -DnewVersion=${{ inputs.version }}

      - name: Git Setup
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      # Add [ignore-conflicts] keyword to commit body message to be read by merge_upstream workflow
      - name: Commit and push
        run: |
          git commit -a \
            -m "chore(versioning): update version to ${{ inputs.version }}" \
            ${{ inputs.merge-upstream-ignoring-conflicts && '-m "[ignore-conflicts]"' || '' }}
          git push
