# This workflow merges changes from downstream branches to upstream branches.
# If a commit contains [ignore-conflicts] in its message, conflicts will be
# automatically resolved using the "ours" merge strategy.
name: Merge Upstream

on:
  workflow_dispatch:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
      - "master"
      - "release-*"
      # Temporary addition to support merge from dev to 12.0.x, will be removed after the release 11.2.0:
      - "dev"
      - "!12.0.x"

jobs:
  merge-upstream:
    uses: bonitasoft/github-workflows/.github/workflows/_reusable_merge_upstream.yml@main
    with:
      # Ignore conflicts if the keyword [ignore-conflicts] is present in the commit message
      ignore-conflicts: ${{ contains(github.event.head_commit.message, '[ignore-conflicts]') }}
    secrets: inherit
